
<div class="row" style="margin-top: 30px">
  <div class="col-lg-12">
    <?php 
      echo $this->flashMessenger()
      ->setMessageOpenFormat('<div%s><p>')
      ->setMessageSeparatorString('</p><p>')
      ->setMessageCloseString('</p></div>')
      ->render('error', ['alert', 'alert-dismissible', 'alert-danger']); 
    ?>
    <?php 
      echo $this->flashMessenger()
      ->setMessageOpenFormat('<div%s><p>')
      ->setMessageSeparatorString('</p><p>')
      ->setMessageCloseString('</p></div>')
      ->render('success', ['alert', 'alert-dismissible', 'alert-success']); 
    ?>
  </div>
</div>

<div class="row" style="margin-top: 30px">
  <div class="col-lg-11">
      <h1>Products</h1>
  </div>
  <div class="col-lg-1 right">
    <a class="btn btn-success btn-xs" href="/products/create">Add</a>
  </div>
</div>

<div class="row">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Title</th>
          <th scope="col">Price</th>
          <th scope="col">Created At</th>
          <th scope="col">Updated At</th>
          <th scope="col">Options</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($products as $key => $product) { ?>
            <tr>
              <th scope="row"><?= $product->getId() ?></th>
              <td><?= $product->getTitle() ?></td>
              <td><?= $product->getPrice() ?></td>
              <td><?= $product->getCreatedAt() ?></td>
              <td><?= $product->getUpdatedAt() ?></td>
              <td>
                <a href="/products/update/<?= $product->getId() ?>">Edit</a>
                -
                <a href="/products/delete/<?= $product->getId() ?>">Delete</a>
              </td>
            </tr>
        <?php } ?>
      </tbody>
    </table>
</div>
